### ISSUE TITLE
Maven code no where to be found!

### ISSUE THREAD

**Issue by UltraGameCoder** [SBPrime/AsyncWorldEdit-API#2]
Link https://github.com/SBPrime/AsyncWorldEdit-Premium/ redirects you to another page which doesn't view the Maven code for the API for the premium version...

**Comment by SBPrime** [comment]
Updated.

**Comment by UltraGameCoder** [comment]
No? There's still no maven code to include in the pom.xml...

**Comment by SBPrime** [comment]
You never mentioned anything about the code to include in the pom. I thought that you meant that the link is incorrect. Check here: https://github.com/SBPrime/AsyncWorldEdit/tree/maven-artifact

**Comment by UltraGameCoder** [comment]
Oh okey. I thought I was clear enough that the promise made on that page wasn't true.

**Comment by UltraGameCoder** [comment]
Thank you for your time!

**Comment by UltraGameCoder** [comment]
1 More problem.
When using code:

```
<!--AsyncWorldEdit Repo-->
       <repository>
           <id>github-asyncworldedit-api</id>
           <url>https://raw.githubusercontent.com/SBPrime/AsyncWorldEdit/maven-artifact/</url>            
	   </repository>
```
and
```
<!--AsyncWorldEdit API-->
    <dependency>
		    <groupId>org.primesoft.asyncworldedit</groupId>
		    <artifactId>AsyncWorldEdit-API</artifactId>
		    <version>[2.2.0-rc-01, 2.2.0)</version>
		    <type>jar</type>
	</dependency>
```
This error gets thrown by the pom.xml:
``Missing artifact org.spigotmc:spigot-api:jar:1.9.4-R0.1-SNAPSHOT (Click for 13 more)``

**Comment by SBPrime** [comment]
I'm not hosting this file and I'm not using it directly.

**Comment by UltraGameCoder** [comment]
oh okey i'll look

**Comment by UltraGameCoder** [comment]
got another error after restarting IDE
``No versions available for com.sk89q.worldedit:wo...,7.1) within specified range (Click for details)``

**Comment by UltraGameCoder** [comment]
Full error:

```
No versions available for com.sk89q.worldedit:worldedit-core:jar:[7.0,7.1) within specified range

org.eclipse.aether.resolution.VersionRangeResolutionException: No versions available for com.sk89q.worldedit:worldedit-core:jar:[7.0,7.1) within specified range
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.filterVersions(DefaultDependencyCollector.java:651)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:396)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:353)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:507)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:460)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:353)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:256)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:282)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:169)
	at org.apache.maven.project.DefaultProjectBuilder.resolveDependencies(DefaultProjectBuilder.java:212)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:185)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:116)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:636)
	at org.eclipse.m2e.core.internal.project.registry.DefaultMavenDependencyResolver.resolveProjectDependencies(DefaultMavenDependencyResolver.java:63)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refreshPhase2(ProjectRegistryManager.java:530)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$3.call(ProjectRegistryManager.java:492)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$3.call(ProjectRegistryManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:496)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:351)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:298)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:405)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:352)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:349)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by UltraGameCoder** [comment]
My pom.xml:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.unlimitedgamesnetwork</groupId>
  <artifactId>UGNSkyblock</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>UGNSkyblock</name>
<url>http://www.unlimitedgamesnetwork.com/</url>
  <build>
      <plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <configuration>
                  <source>1.7</source>
                  <target>1.7</target>
              </configuration>
          </plugin>
      </plugins>
   </build>
   <repositories>
   	   <!--Spigot Repo-->
       <repository>
           <id>spigot-repo</id>
           <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
       </repository>
       <!--AsyncWorldEdit Repo-->
       <repository>
           <id>github-asyncworldedit-api</id>
           <url>https://raw.githubusercontent.com/SBPrime/AsyncWorldEdit/maven-artifact/</url>            
	   </repository>
   </repositories>
   <dependencies>
    <!--Spigot API-->
    <dependency>
           <groupId>org.spigotmc</groupId>
           <artifactId>spigot-api</artifactId>
           <version>1.9.4-R0.1-SNAPSHOT</version>
           <scope>provided</scope>
    </dependency>
    <!--Bukkit API-->
    <dependency>
            <groupId>org.bukkit</groupId>
            <artifactId>bukkit</artifactId>
            <version>1.9.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
    </dependency>
    <!--AsyncWorldEdit API-->
    <dependency>
		    <groupId>org.primesoft.asyncworldedit</groupId>
		    <artifactId>AsyncWorldEdit-API</artifactId>
		    <version>[2.2.0-rc-01, 2.2.0)</version>
		    <type>jar</type>
	</dependency>
</dependencies>
</project>
```
And included jars: ``spigot-1.9.4-R0.1-SNAPSHOT-latest.jar``

**Comment by UltraGameCoder** [comment]
Do you know how to fix this?

**Comment by UltraGameCoder** [comment]
I would really appreciate your help.

**Comment by SBPrime** [comment]
You need to add the WorldEdit repo. You can check how I have the pom setup in AWE here: https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/pom.xml

Also what exactly are you trying to do?

**Comment by UltraGameCoder** [comment]
Im making a plugin which load/saves schematics of player's builds.
So when they leave the server. their area gets saved.
And gets loaded on join.

**Comment by UltraGameCoder** [comment]
I can't tell much about the details because its confidential.

**Comment by UltraGameCoder** [comment]
But the above description tells pretty much the part of which AWE comes into action

**Comment by UltraGameCoder** [comment]
I keep adding stuff to my pom.xml.
now it error because junit isn;t included.
then jcronicles or something. then spigotjar. and so forth and so forth.
do you know why?

My current pom:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.unlimitedgamesnetwork</groupId>
  <artifactId>UGNSkyblock</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>UGNSkyblock</name>
<url>http://www.unlimitedgamesnetwork.com/</url>
  <build>
      <plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <configuration>
                  <source>1.7</source>
                  <target>1.7</target>
              </configuration>
          </plugin>
      </plugins>
   </build>
   <repositories>
   	   <!--Spigot Repo-->
       <repository>
           <id>spigot-repo</id>
           <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
       </repository>
       <!--AsyncWorldEdit Repo-->
       <repository>
           <id>github-asyncworldedit-api</id>
           <url>https://raw.githubusercontent.com/SBPrime/AsyncWorldEdit/maven-artifact/</url>            
	   </repository>
	   <!--Worldedit/Worldguard Repo-->
	   <repository>
        <id>sk89q-repo</id>
        <url>http://maven.sk89q.com/repo/</url>
    </repository>
   </repositories>
   <dependencies>
    <!--Spigot API-->
    <dependency>
           <groupId>org.spigotmc</groupId>
           <artifactId>spigot-api</artifactId>
           <version>1.9.4-R0.1-SNAPSHOT</version>
           <scope>provided</scope>
    </dependency>
    <!--AsyncWorldedit API-->
    <dependency>
		    <groupId>org.primesoft.asyncworldedit</groupId>
		    <artifactId>AsyncWorldEdit-API</artifactId>
		    <version>[2.2.0-rc-01, 2.2.0)</version>
		    <type>jar</type>
	</dependency>
	<!--Worldguard API-->
	<dependency>
        <groupId>com.sk89q.worldguard</groupId>
        <artifactId>worldguard-core</artifactId>
        <version>7.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>com.sk89q.worldguard</groupId>
        <artifactId>worldguard-legacy</artifactId>
        <version>7.0.0-SNAPSHOT</version>
    </dependency>
	<!--Worldedit API-->
    <dependency>
            <groupId>com.sk89q.worldedit</groupId>
            <artifactId>worldedit-bukkit</artifactId>
            <version>7.0.0-SNAPSHOT</version>
            <scope>provided</scope>
    </dependency>
    <dependency>
            <groupId>com.sk89q.worldedit</groupId>
            <artifactId>worldedit-core</artifactId>
            <version>7.0.0-SNAPSHOT</version>
            <scope>provided</scope>
    </dependency>
</dependencies>
</project>
```

**Comment by SBPrime** [comment]
A tip: I use local jars for missing and dev dependencies.
